<a href="https://colab.research.google.com/github/fantajeon/DLPytorch1.2/blob/master/Chapter1_Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PyTorch의 Tensor란?

PyTorch의 텐서를 살펴보겠습니다.

Author: fantajeon@gmail.com

In [3]:
import torch
torch.__version__

'1.1.0'

Tensor는 한가지 데이터 타입으로 구성된 다차원 배열을 의미합니다.
PyTorch에서는 CPU와 GPU tensor 타입을 지원합니다.


1. 스칼라: 차원이 0
2. 벡터: 차원이 1
3. 행렬: 차원이 2
4. .......



# Tensor 생성방법

**Tensor는 여러가지 방식으로 생성할 수 있습니다.**

In [4]:
torch.tensor( [0,1,2,3,4], dtype=torch.int32) # python list를 통한 생성

tensor([0, 1, 2, 3, 4], dtype=torch.int32)

In [5]:
torch.zeros([3,5], dtype=torch.float32)  # 내장된 함수로 생성

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [6]:
torch.ones([3,5], dtype=torch.float32)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [8]:
x = torch.tensor([2.0])
print(x)  # tensor 출력
print(x.item())   # Tensor --> Python 숫자 얻는 법

tensor([2.])
2.0


In [58]:
print("dim", torch.rand([]).dim() )  # 0차원 랜덤 텐서
print("dim", torch.rand(10).dim() )  # 길이가 10인 1차원 랜덤 텐서
print("dim", torch.rand(3,10).dim() )   # 길이가 3,10인 2차원 랜덤 텐서
print("dim", torch.rand(3,4,5,4,3,2).dim() )   # 길이가 3,4,5,3,2인 6차원 랜덤 텐서

dim 0
dim 1
dim 2
dim 6


Numpy는 Python에서 공학계산에 필요한 기본 수치해석 라이브러리입니다. 보통은 다른 Python library(matplotlib)들이 직접적으로 PyTorch의 tensor와 호환이 되질 않습니다. 그러나 numpy는 상대적으로 더 잘됩니다. 그래서 많은 machine learning 개발자들은 numpy를 혼용해서 사용합니다.


In [10]:
import numpy as np

np_x = np.array( [[1,2,3], [4,5,6]], dtype=np.float32 )
torch.tensor(np_x)      # numpy로부터 tensor를 생성하는 방법


tensor([[1., 2., 3.],
        [4., 5., 6.]])

# 차원과 Tensor


In [20]:
torch.tensor(1.9).dim()    # 0차원 --> 스칼리입니다.

0

In [25]:
torch.tensor([1.9]).dim()  # 1차원 --> 개수가 1개인 벡터입니다.

1

In [26]:
torch.tensor([1.9, 2.0]).dim()  # 1차원 --> 개수가 2개인 벡터입니다.

1

In [31]:
torch.tensor([[1.9, 2.0, 2.1],[3.0, 4.0, 5.0]]).dim()  # 2차원 --> 2x2인 행렬입니다.

2

자 그러면은 흑백 사진은 차원이 어떻게 될까요? 예를들어 800 x 600 흑백 사진이 있습니다. 

흑백 사진의 차원은 2차원 입니다. 그대신 각 차원마다 길이가 다른 것입니다.

In [45]:
gray_image = torch.rand( 800,600, dtype=torch.float32 )
print(gray_image)
print("dim", gray_image.dim())

tensor([[0.0101, 0.5041, 0.4162,  ..., 0.0965, 0.2694, 0.3579],
        [0.0528, 0.5480, 0.0867,  ..., 0.4708, 0.2864, 0.7728],
        [0.1458, 0.1161, 0.7831,  ..., 0.9851, 0.3977, 0.3618],
        ...,
        [0.8248, 0.8539, 0.3579,  ..., 0.0632, 0.1759, 0.6595],
        [0.7002, 0.4647, 0.3156,  ..., 0.4022, 0.8550, 0.6755],
        [0.6247, 0.7247, 0.9561,  ..., 0.8256, 0.9608, 0.9950]])
dim 2


이제 컬러사진 800x600은 어떻게 표현을 할까요? 컬러 사진은 보통 3원색(Red,Green,Blue)을 가집니다.

In [46]:
color_image = torch.rand( 800,600,3, dtype=torch.float32 )
print("dim", color_image.dim())

dim 3


여러장의 사진을 묶어서 표현하려면 예를들어 32장의 컬러 사진을 tensor로 표현하고 싶습니다. 

보통 32장을 배치축(**batch axis**)라고 합니다. 기계가 학습을 할때 여러개의 샘플을 모아서 학습합니다.

In [48]:
batch_color_image = torch.rand( 32,320,640,3, dtype=torch.float32 )
print("dim", batch_color_image.dim())

dim 4


지금까지 다음의 과정을 학습하였습니다:
1. tensor는 다차원 배열입니다.
2. Python list으로부터 직접적으로 tensor를 생성하는 방법
3. Numpy으로부터 tensor를 생성하는 방법
4. 스칼라,벡터,행렬,흑백과 컬러 사진 형태를 tensor로 표현하는 방법

끝까지 읽어주셔서, 감사합니다.